language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -q -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - sudo rm -f /etc/boto.cfg
  - pytest --cov=ptsplitter
after_success:
  - codecov
